server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myauction_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
pagehelper:
  helper-dialect: mysql
  reasonable: true
